#!/bin/sh

IP=`ifconfig|head -1|sed -e "s/^\(.*\) \s .*/\1/g"|xargs -I% ifconfig % |grep -E '([1-2]?[0-9]{0,2}\.){3,3}[1-2]?[0-9]{0,2}'`

if [$IP = ""]; then
    IP=`ifconfig|egrep -o '([1-2]?[0-9]{0,2}\.){3,3}[1-2]?[0-9]{0,2}'|sed -n 3p`
fi
echo $IP
