---
- name: Check nmcli device status
  shell: nmcli device show
  changed_when: no
  always_run: yes
  register: res

- block:
  - name: Create bond0
    shell: nmcli c add type bond ifname bond0 con-name bond-bond0 mode active-backup
    when: res.stdout.find('bond-bond0') == -1

  - name: Configure bond0
    shell: nmcli c mod bond-bond0 ipv4.method disabled ipv6.method ignore
    when: res.stdout.find('bond-bond0') == -1

  - name: Add bond-slave eno2
    shell: nmcli c add type bond-slave ifname eno2 con-name bond-slave-eno2 master bond0
    when: res.stdout.find('bond-slave-eno2') == -1

  - name: Add bond-slave eno4
    shell: nmcli c add type bond-slave ifname eno4 con-name bond-slave-eno4 master bond0
    when: res.stdout.find('bond-slave-eno4') == -1

  - name: Create vlan10
    shell: nmcli c add type vlan ifname vlan10 con-name vlan-vlan10 dev bond0 id 10
    when: res.stdout.find('vlan-vlan10') == -1

  - name: Configure vlan10
    shell: nmcli c mod vlan-vlan10 ipv4.method manual ipv4.address "{{ vlan10_ip }}" ipv4.route-metric 0 ipv4.never-default no
    when: res.stdout.find('{{ vlan10_ip }}') == -1

  - name: Create vlan13
    shell: nmcli c add type vlan ifname vlan13 con-name vlan-vlan13 dev bond0 id 13
    when: res.stdout.find('vlan-vlan13') == -1

  - name: Configure vlan13
    shell: nmcli c mod vlan-vlan13 ipv4.method manual ipv4.address "{{ vlan13_ip }}" ipv4.route-metric 0 ipv4.never-default yes
    when: res.stdout.find('{{ vlan13_ip }}') == -1

  - name: Create vlan15
    shell: nmcli c add type vlan ifname vlan15 con-name vlan-vlan15 dev bond0 id 15
    when: res.stdout.find('vlan-vlan15') == -1

  - name: Configure vlan15
    shell: nmcli c mod vlan-vlan15 ipv4.method manual ipv4.address "{{ vlan15_ip }}" ipv4.route-metric 0 ipv4.never-default yes
    when: res.stdout.find('{{ vlan15_ip }}') == -1

  - name: Create vlan11
    shell: nmcli c add type vlan ifname vlan11 con-name vlan-vlan11 dev bond0 id 11
    when: res.stdout.find('vlan-vlan11') == -1

  - name: Configure vlan11
    shell: nmcli c mod vlan-vlan11 ipv4.method manual ipv4.address "{{ vlan11_ip }}" ipv4.route-metric 0 ipv4.never-default yes
    when: res.stdout.find('{{ vlan15_ip }}') == -1

#  - name: Reboot
#    shell: reboot

  become: yes
  become_method: sudo
