---
- block:

# package
  - name: Yum Update
    yum: name=* state=latest
    when: ansible_distribution == "RedHat" 

  - name: Apt Update
    apt:
      update_cache=yes
      upgrade=yes
    when: ansible_distribution == "Ubuntu" 

  - name: Yum install ntp
    yum: name=ntp state=latest
    when: ansible_distribution == "RedHat" 

# user&group
  - group: name=ansible gid=700 state=present

  - name: Create User
    user:
      name=ansible
      uid=700
      group=ansible
      groups=ansible,sudo
      password=$6$Bgk0TqcV33qDM$MZMyhEOpgfMNc3ZgWURmDW7.vJ3qOyTD1mMNw4VOAx3o5JSM2C8qszRpg2F4qWB5N7xxBjjhIZAmdd7GHJ7x20

# mkdir
  - name: Create swift directory
    file: path=/srv/node/{{ item }} state=directory owner=swift group=swift mode=0755
    with_items:
      - sdb1
      - sdc1
      - sdd1
      - sde1
      - sdf1
      - sdg1

# template
  - name: Configure fstab
    template: src=fstab.j2 dest=/etc/fstab

#shells
  - name: Check nmcli device status
    shell: nmcli device show
    changed_when: no
    always_run: yes
    register: res

  - name: Configure vlan11
    shell: nmcli c mod vlan-vlan11 ipv4.method manual ipv4.address "{{ vlan11_ip }}" ipv4.route-metric 0 ipv4.never-default yes
    when: res.stdout.find('{{ vlan15_ip }}') == -1

  - name: Stopped chronyd
    shell: systemctl stop chronyd

  - name: Disable chronyd
    shell: systemctl disable chronyd

  - name: Start ntp
    shell: systemctl start ntpd

  - name: Enable ntp
    shell: systemctl enable ntpd

  - name: include vars
    include_vars: "template.yml"



  become: yes
  become_method: sudo

